### ISSUE TITLE
Create use case: Log out

### ISSUE THREAD

**Issue by Skellyboy38** [Skellyboy38/SOEN-343-NullPointer#8]
Use this example from the slides when creating the use case description:

Fully-dressed example: Process Sale
Use case UC1: Process Sale
Primary Actor: Cashier
Stakeholders and Interests: Cashier: Wants accurate and fast entry,
no payment errors, …
Salesperson: Wants sales commissions updated.
…
Preconditions: Cashier is identified and authenticated.
Success Guarantee (Postconditions):
Sale is saved. Tax correctly calculated.
…
Main success scenario (or basic flow): [see next slide]
Extensions (or alternative flows): [see next slide]
Special requirements: Touch screen UI, …
Technology and Data Variations List:
Identifier entered by bar code scanner,…
Open issues: What are the tax law variations? …

**Comment by McGiver-** [comment]
[useCase_logout.txt](https://github.com/Skellyboy38/SOEN-343-NullPointer/files/481124/useCase_logout.txt)

**Comment by Daviddube** [comment]
Minor typo in first step (loggout should be logout). Other than that, looks good!

**Comment by McGiver-** [comment]
Fixed typo.
